# Site settings
port: 4000
title: PiCrate gem
email: mamba2928@yahoo.co.uk
description: > # this means to ignore newlines until "baseurl:"
  The picrate gem is ruby wrapper around processing, targetting raspberrypi and
  linux
baseurl: "" # the subpath of your site, e.g. /blog
regenerate: true
url: "https://ruby-processing.github.io/PiCrate"

urls:
  bugs: https://github.com/ruby-processing/PiCrate/issues
  github: https://github.com/ruby-processing/PiCrate/
  wiki: https://github.com/ruby-processing/PiCrate/wiki
twitter_username: monkstoneT
github_username:  monkstone
# Build settings
markdown: kramdown
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

include: [collections]
collections:
  blocks:
    output: true
    permalink: /blocks/index.html
  classes:
    output: true
    permalink: /classes/index.html
  editors:
    output: true
    permalink: /editors/index.html
  methods:
    output: true
    permalink: /methods/index.html
  gems:
    output: true
    permalink: /gems/index.html
  libraries:
    output: true
    permalink: /libraries/index.html
  live:
    output: true
    permalink: /live/index.html
  modules:
    output: true
    permalink: /modules/index.html
  magic:
    output: true
    permalink: /magic/index.html
  objects:
    output: true
    permalink: /objects/index.html

syntax-highlighting:
  enabled: true

sass:
  sass_dir: _sass
