# Site settings
port: 4000
title: PiCrate gem
email: mamba2928@yahoo.co.uk
description: > # this means to ignore newlines until "baseurl:"
  The picrate gem is ruby wrapper around processing, targetting raspberrypi and
  linux
baseurl: "" # the subpath of your site, e.g. /blog
regenerate: true
url: "https://ruby-processing.github.io/PiCrate"

urls:
  bugs: https://github.com/ruby-processing/PiCrate/issues
  github: https://github.com/ruby-processing/PiCrate/
  wiki: https://github.com/ruby-processing/PiCrate/wiki
twitter_username: monkstoneT
github_username:  monkstone

syntax-highlighting:
  enabled: true

sass:
  sass_dir: _sass

# Build settings
markdown: kramdown
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
